### ISSUE TITLE
[Bug]: Hitting RuntimeError: collective nonSFG is not supported during hpu graph capturing

### ISSUE THREAD

**Issue by vermavis** [HabanaAI/vllm-fork#495]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
python3 collect_env.py
/usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, types.FunctionType)
Collecting environment information...
PyTorch version: 2.4.0a0+git74cd574
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               160
On-line CPU(s) list:                  0-159
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
CPU family:                           6
Model:                                106
Thread(s) per core:                   2
Core(s) per socket:                   40
Socket(s):                            2
Stepping:                             6
CPU max MHz:                          3400.0000
CPU min MHz:                          800.0000
BogoMIPS:                             4600.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            3.8 MiB (80 instances)
L1i cache:                            2.5 MiB (80 instances)
L2 cache:                             100 MiB (80 instances)
L3 cache:                             120 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-39,80-119
NUMA node1 CPU(s):                    40-79,120-159
Vulnerability Gather data sampling:   Mitigation; Microcode
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] habana-torch-dataloader==1.18.0.524
[pip3] habana-torch-plugin==1.18.0.524
[pip3] numpy==1.23.5
[pip3] pynvml==8.0.4
[pip3] pytorch-lightning==2.4.0
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0a0+git74cd574
[pip3] torch_tb_profiler==0.4.0
[pip3] torchaudio==2.4.0a0+69d4077
[pip3] torchdata==0.7.1+5e6f7b7
[pip3] torchmetrics==1.4.2
[pip3] torchtext==0.18.0a0+9bed85d
[pip3] torchvision==0.19.0a0+48b1edf
[pip3] transformers==4.46.2
[pip3] triton==3.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.3.post1+gaudi118
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

LD_LIBRARY_PATH=/opt/habanalabs/libfabric-1.22.0/lib:/opt/amazon/openmpi/lib:/usr/lib/habanalabs:
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### 🐛 Describe the bug

```
import sys
from vllm import LLM, SamplingParams

model_name =  "meta-llama/Meta-Llama-3.1-70B"

model = LLM(model_name, max_model_len=16384, tensor_parallel_size=4)
```

I got 8x Gaudi2's on the host, using LAZY mode (all default settings)..

Hitting:

```
(RayWorkerWrapper pid=35827) INFO 11-13 17:03:45 habana_model_runner.py:1587] Using 10.23 GiB/13.1 GiB of free device memory for HPUGraphs, 5.114 GiB for prompt and 5.114 GiB for decode (VLLM_GRAPH_PROMPT_RATIO=0.5)
(RayWorkerWrapper pid=35827) INFO 11-13 17:03:45 habana_model_runner.py:1428] [Warmup][Graph/Prompt][1/31] batch_size:1 num_blocks:128 free_mem:13.1 GiB
ERROR 11-13 17:03:45 worker_base.py:382] Error executing method initialize_cache. This might cause deadlock in distributed execution.
ERROR 11-13 17:03:45 worker_base.py:382] Traceback (most recent call last):
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/worker_base.py", line 374, in execute_method
ERROR 11-13 17:03:45 worker_base.py:382]     return executor(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_worker.py", line 202, in initialize_cache
ERROR 11-13 17:03:45 worker_base.py:382]     self._warm_up_model()
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_worker.py", line 220, in _warm_up_model
ERROR 11-13 17:03:45 worker_base.py:382]     self.model_runner.warmup_model(self.hpu_cache[0])
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-13 17:03:45 worker_base.py:382]     return func(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_model_runner.py", line 1593, in warmup_model
ERROR 11-13 17:03:45 worker_base.py:382]     self.warmup_graphs(
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_model_runner.py", line 1472, in warmup_graphs
ERROR 11-13 17:03:45 worker_base.py:382]     self.warmup_scenario(batch_size, seq_len, is_prompt, kv_caches)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_model_runner.py", line 1378, in warmup_scenario
ERROR 11-13 17:03:45 worker_base.py:382]     self.execute_model(inputs, kv_caches, warmup_mode=True)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-13 17:03:45 worker_base.py:382]     return func(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_model_runner.py", line 1934, in execute_model
ERROR 11-13 17:03:45 worker_base.py:382]     hidden_states = self.model.forward(
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 726, in forward
ERROR 11-13 17:03:45 worker_base.py:382]     return wrapped_hpugraph_forward(
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 599, in wrapped_hpugraph_forward
ERROR 11-13 17:03:45 worker_base.py:382]     outputs = orig_fwd(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/worker/habana_model_runner.py", line 315, in forward
ERROR 11-13 17:03:45 worker_base.py:382]     hidden_states = self.model(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1556, in _wrapped_call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     return self._call_impl(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1565, in _call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     return forward_call(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/model_executor/models/llama.py", line 431, in forward
ERROR 11-13 17:03:45 worker_base.py:382]     model_output = self.model(input_ids, positions, kv_caches,
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1556, in _wrapped_call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     return self._call_impl(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1606, in _call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     result = forward_call(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/model_executor/models/llama.py", line 316, in forward
ERROR 11-13 17:03:45 worker_base.py:382]     hidden_states = self.get_input_embeddings(input_ids)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/model_executor/models/llama.py", line 301, in get_input_embeddings
ERROR 11-13 17:03:45 worker_base.py:382]     return self.embed_tokens(input_ids)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1556, in _wrapped_call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     return self._call_impl(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1606, in _call_impl
ERROR 11-13 17:03:45 worker_base.py:382]     result = forward_call(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/model_executor/layers/vocab_parallel_embedding.py", line 365, in forward
ERROR 11-13 17:03:45 worker_base.py:382]     output = tensor_model_parallel_all_reduce(output_parallel)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/distributed/communication_op.py", line 11, in tensor_model_parallel_all_reduce
ERROR 11-13 17:03:45 worker_base.py:382]     return get_tp_group().all_reduce(input_)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/distributed/parallel_state.py", line 317, in all_reduce
ERROR 11-13 17:03:45 worker_base.py:382]     return hpu_comm.all_reduce(input_)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/vllm-fork/vllm/distributed/device_communicators/hpu_communicator.py", line 26, in all_reduce
ERROR 11-13 17:03:45 worker_base.py:382]     dist.all_reduce(x, group=self.group)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
ERROR 11-13 17:03:45 worker_base.py:382]     return func(*args, **kwargs)
ERROR 11-13 17:03:45 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2296, in all_reduce
ERROR 11-13 17:03:45 worker_base.py:382]     work = group.allreduce([tensor], opts)
ERROR 11-13 17:03:45 worker_base.py:382] RuntimeError: collective nonSFG is not supported during hpu graph capturing
[rank0]: Traceback (most recent call last):
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by vermavis** [comment]
This got resolved when using:
`enforce_eager=True` along with LAZY mode.

**Comment by michalkuligowski** [comment]
Hi @vermavis do you set PT_HPU_ENABLE_LAZY_COLLECTIVES or ‎PT_HPU_LAZY_MODE as described in https://docs.habana.ai/en/latest/PyTorch/Inference_on_PyTorch/Inference_Using_HPU_Graphs.html?highlight=pt_hpu_enable_lazy_collectives#run-inference-using-hpu-graphs 
For available runtime mode please refer to https://github.com/HabanaAI/vllm-fork/blob/habana_main/README_GAUDI.md#execution-modes

**Comment by vermavis** [comment]
yes PT_HPU_LAZY_MODE was set to 1 by default. Out of the 4 execution modes, the Pytorch Lazy Mode seem to make it work.

**Comment by xuechendi** [comment]
@vermavis , if you want to use non-eager mode, you have to use "PT_HPU_ENABLE_LAZY_COLLECTIVES=1" 
=> enable/disable this env impoprts different hccl library.

**Comment by michalkuligowski** [comment]
@vermavis can this issue be closed?

**Comment by vermavis** [comment]
yup this can be closed. I verified it worked for me:

```
(RayWorkerWrapper pid=181084) INFO 11-15 13:58:09 hpu_model_runner.py:1762] Warmup finished in 567 secs, allocated 813.4 MiB of device memory [repeated 6x across cluster]
(RayWorkerWrapper pid=181095) ============================= HABANA PT BRIDGE CONFIGURATION ===========================  [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_LAZY_MODE = 1 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_RECIPE_CACHE_PATH =  [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_CACHE_FOLDER_DELETE = 0 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_RECIPE_CACHE_CONFIG =  [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_LAZY_ACC_PAR_MODE = 1 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_EAGER_PIPELINE_ENABLE = 1 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095)  PT_HPU_EAGER_COLLECTIVE_PIPELINE_ENABLE = 1 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095) ---------------------------: System Configuration :--------------------------- [repeated 6x across cluster]
(RayWorkerWrapper pid=181095) Num CPU Cores : 160 [repeated 6x across cluster]
(RayWorkerWrapper pid=181095) CPU RAM       : 1056374408 KB [repeated 6x across cluster]
(RayWorkerWrapper pid=181095) ------------------------------------------------------------------------------ [repeated 6x across cluster]
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
